apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring-sock-shop
  labels:
    app: grafana
    component: core
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31526
  selector:
    app: grafana
    component: core
